Support color correction for img2img and inpainting
lstein/stable-diffusion pull request #613
Opened 2022-09-16 14:15 UTC by db3000

Fixes #552

Perform image color correction, borrowed from https://github.com/Pyr-000/YetAnotherStableDiffusion/commit/c7bf958c2dfa88fc027690983fee1f877e8827e9

Note that the correction needs to be done against a stable initial image when running img2img or inpainting multiple times. If the correction is done only against the previous image, you end up with everything turning cyan, as in https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/481

Using tests from that ticket, before correction:
![out2](https://user-images.githubusercontent.com/4308379/190659896-f999610e-54c2-4426-a943-cd661a33c615.png)

After correction:
![out](https://user-images.githubusercontent.com/4308379/190660016-f97a868c-228b-4160-b76a-1b678c522acb.png)

2022-09-16 21:19 UTC, lstein requested changes
This looks fine, but recent changes to how the command-line arguments are stored and parsed prevent it from being merged automatically. The argument parsing now lives in ldm/dream/args.py If you can, could you rebase against current development and resolve the conflicts?

Thanks!

2022-09-16 22:56 UTC, db3000 commented
Thanks, rebased against development. Seems my test script needed to be changed as it was hitting a new issue: https://github.com/lstein/stable-diffusion/issues/628

2022-09-17 22:40 UTC, lstein commented
#628 is fixed by PR #654, which should go in very soon. I'll run some testing on your PR tomorrow (Sunday) and if all goes well it'll go into dev. Thanks so much for the rebasing!

2022-09-18 13:46 UTC, lstein approved these changes
It seems to be working as advertised. 

In general, the quality of the images is getting degraded with multiple passes through img2img, and I wonder if this reflects over-aggressive compression when writing out the PNGs. Better still would be for a way to keep the uncompressed image in memory while operating on it, rather than writing it out to disk each time.

2022-09-18 13:46 UTC, lstein commented on backend/modules/parameters.py
> +    if 'init_color' in params and len(params['init_color']) > 0:
Aside for @Kyle0654: Here's an example of a PR that has had to make parallel changes among the web and CLI interfaces in order to introduce a new switch. I'm looking forward to you unifying the command-line argument processing in the new architecture.

2022-09-18 13:47 UTC, merged

2022-09-18 14:05 UTC, db3000 commented
Thanks! Yeah I saw that as well, I thought that was further artifacts of the diffusion process. Could validate that by skipping the actual processing and seeing if the artifacts appear still?